package:
  name: nexpy
  version: "0.10.12"

source:
  git_url: https://github.com/nexpy/nexpy.git
  git_tag: v0.10.12

build:
  entry_points:
    - nexpy = nexpy.nexpygui:main
  number: 0
# osx_is_app: True
  osx_is_app: True

requirements:
  build:
    - python
    - setuptools
    - nexusformat >=0.4.18
    - numpy >=1.6.0
    - scipy
    - h5py
    - jupyter
    - ipython >=4.0.0
    - matplotlib >=1.5.0
    - pyqt
    - six
    - ansi2html

  run:
    - python
    - nexusformat >=0.4.18
    - numpy >=1.6.0
    - scipy
    - h5py
    - jupyter
    - ipython >=4.0.0
    - matplotlib >=1.5.0
    - pyqt
    - ansi2html

test:
  imports:
    - nexpy
    - nexpy.api
    - nexpy.api.frills
    - nexpy.api.frills.functions
    - nexpy.definitions
    - nexpy.gui
    - nexpy.plugins
    - nexpy.readers

  commands:
    - nexpy --help

about:
  home: http://nexpy.github.io/nexpy/
  license: BSD License
  summary: 'NeXpy: A Python GUI to analyze NeXus data'
