package:
  name: nexpy
  version: "0.12.5"

source:
  git_url: https://github.com/nexpy/nexpy.git
  git_tag: v0.12.5

build:
  entry_points:
    - nexpy = nexpy.nexpygui:main
  number: 0
  noarch: "python"

requirements:
  build:
    - python
    - setuptools
    - nexusformat >=0.5.2
    - numpy
    - scipy
    - h5py
    - qtpy
    - qtconsole
    - matplotlib
    - six
    - ansi2html

  run:
    - python
    - nexusformat >=0.5.2
    - numpy
    - scipy
    - h5py
    - qtpy
    - qtconsole
    - matplotlib
    - ansi2html

test:
  imports:
    - nexpy
    - nexpy.api
    - nexpy.api.frills
    - nexpy.api.frills.functions
    - nexpy.definitions
    - nexpy.gui
    - nexpy.plugins
    - nexpy.readers

  commands:
    - nexpy --help

about:
  home: "http://nexpy.github.io/nexpy/"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "COPYING"
  summary: "NeXpy: A Python GUI to analyze NeXus data"
  doc_url: "https://nexpy.github.io/nexpy/"
  dev_url: "https://github.com/nexpy/nexpy"
