package:
  name: nexpy
  version: "0.12.1"

source:
  git_url: https://github.com/nexpy/nexpy.git
  git_tag: v0.12.1

build:
  entry_points:
    - nexpy = nexpy.nexpygui:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - nexusformat >=0.5.0
    - numpy
    - scipy
    - h5py
    - jupyter
    - ipython
    - matplotlib
    - pyqt
    - six
    - ansi2html

  run:
    - python
    - nexusformat
    - numpy
    - scipy
    - h5py
    - jupyter
    - ipython
    - matplotlib
    - pyqt
    - ansi2html

test:
  imports:
    - nexpy
    - nexpy.api
    - nexpy.api.frills
    - nexpy.api.frills.functions
    - nexpy.definitions
    - nexpy.gui
    - nexpy.plugins
    - nexpy.readers

  commands:
    - nexpy --help

about:
  home: http://nexpy.github.io/nexpy/
  license: BSD License
  summary: 'NeXpy: A Python GUI to analyze NeXus data'
